import PDFDocument from 'pdfkit';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { env } from '../config/env.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FONTS_DIR = path.join(__dirname, '../assets/fonts');

const FONT_PATHS = {
  regular: path.join(FONTS_DIR, 'NotoSans-Regular.ttf'),
  bold: path.join(FONTS_DIR, 'NotoSans-Bold.ttf'),
  devanagariRegular: path.join(FONTS_DIR, 'NotoSansDevanagari-Regular.ttf'),
  devanagariBold: path.join(FONTS_DIR, 'NotoSansDevanagari-Bold.ttf')
};

// Verify font existence or fallback to standard Helvetica
const HAS_CUSTOM_FONTS =
  fs.existsSync(FONT_PATHS.regular) &&
  fs.existsSync(FONT_PATHS.bold) &&
  fs.existsSync(FONT_PATHS.devanagariRegular);

/**
 * Checks if a string contains Devanagari (Hindi, Marathi, Sanskrit, etc.) characters
 */
export function containsDevanagari(text) {
  return typeof text === 'string' && /[\u0900-\u097F]/.test(text);
}

/**
 * Checks if a string contains characters outside Latin, Common, and Devanagari
 */
export function containsUnsupportedScript(text) {
  if (typeof text !== 'string') return false;
  // Allows basic Latin, Latin-1 supplement, Devanagari, standard punctuation, math symbols, currency, box drawing
  const supportedRegex = /^[\u0000-\u024F\u0900-\u097F\u2000-\u206F\u20A0-\u20CF\u2100-\u214F\u25A0-\u25FF\u2700-\u27BF\s\d]*$/;
  return !supportedRegex.test(text);
}

/**
 * Generates a safe, sanitized filename for PDF downloads
 */
export function sanitizePdfFilename(title, suffix = '') {
  const safeTitle = (title || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'untitled';
  const safeSuffix = suffix ? `-${suffix.toLowerCase().replace(/[^a-z0-9]+/g, '-')}` : '';
  return `${safeTitle}${safeSuffix}.pdf`;
}

/**
 * Registers fonts and returns font helper
 */
function setupDocumentFonts(doc) {
  if (HAS_CUSTOM_FONTS) {
    doc.registerFont('NotoSans', FONT_PATHS.regular);
    doc.registerFont('NotoSans-Bold', FONT_PATHS.bold);
    doc.registerFont('NotoDevanagari', FONT_PATHS.devanagariRegular);
    doc.registerFont('NotoDevanagari-Bold', FONT_PATHS.devanagariBold || FONT_PATHS.devanagariRegular);
  }

  return {
    getFont: (text, isBold = false) => {
      if (!HAS_CUSTOM_FONTS) {
        return isBold ? 'Helvetica-Bold' : 'Helvetica';
      }
      if (containsDevanagari(text)) {
        return isBold ? 'NotoDevanagari-Bold' : 'NotoDevanagari';
      }
      return isBold ? 'NotoSans-Bold' : 'NotoSans';
    }
  };
}

/**
 * Stamps "Page X of Y" and "Generated by ReviseLive" on all buffered pages
 */
function stampFooters(doc) {
  const range = doc.bufferedPageRange();
  const fontName = HAS_CUSTOM_FONTS ? 'NotoSans' : 'Helvetica';

  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const pageNum = i - range.start + 1;
    const totalPages = range.count;

    doc.save();
    doc.font(fontName).fontSize(8).fillColor('#64748b'); // slate-500
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      40,
      doc.page.height - 30,
      { width: doc.page.width - 80, align: 'right' }
    );
    doc.text(
      'Generated by ReviseLive',
      40,
      doc.page.height - 30,
      { width: doc.page.width - 80, align: 'left' }
    );
    doc.restore();
  }
}

/**
 * Ensures enough vertical space on page, adding a new page if necessary
 */
function ensureVerticalSpace(doc, requiredHeight) {
  const bottomMargin = doc.page.margins.bottom || 40;
  const availableSpace = doc.page.height - bottomMargin - doc.y;
  if (availableSpace < requiredHeight) {
    doc.addPage();
  }
}

/**
 * Generates Quiz Question Paper or Answer Key PDF (F6)
 * Returns a readable stream
 */
export function generateQuizPdf(quiz, { variant = 'questions', explanations = true } = {}) {
  const isAnswerKey = variant === 'answers';
  const metadataTitle = `${quiz.title || 'Quiz'} - ${isAnswerKey ? 'Answer Key' : 'Questions'}`;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 40, bottom: 40, left: 40, right: 40 },
    bufferPages: true,
    info: {
      Title: metadataTitle,
      Author: 'ReviseLive',
      Subject: quiz.topic || 'Revision',
      Creator: 'ReviseLive Education Engine'
    }
  });

  const { getFont } = setupDocumentFonts(doc);

  // Check script coverage across quiz
  let scriptWarning = false;
  const allTexts = [quiz.title, quiz.description || ''];
  (quiz.questions || []).forEach((q) => {
    allTexts.push(q.questionText || '');
    (q.options || []).forEach((opt) => allTexts.push(opt || ''));
  });
  if (allTexts.some((t) => containsUnsupportedScript(t))) {
    scriptWarning = true;
  }

  // Header
  if (scriptWarning) {
    doc.save();
    doc.rect(40, doc.y, doc.page.width - 80, 20).fill('#fef3c7'); // amber-100
    doc.font(getFont('Warning', false)).fontSize(8).fillColor('#92400e').text(
      'Notice: This quiz contains characters from a script that may not be fully supported by the bundled font set.',
      45,
      doc.y - 15,
      { width: doc.page.width - 90 }
    );
    doc.restore();
    doc.moveDown(0.8);
  }

  // Quiz Title
  const titleFont = getFont(quiz.title, true);
  doc.font(titleFont).fontSize(18).fillColor('#0f172a').text(quiz.title || 'Untitled Quiz', { align: 'left' });
  doc.moveDown(0.3);

  // Subtitle / Topic
  const topicText = quiz.topic ? `Topic: ${quiz.topic}` : '';
  const countText = `Questions: ${quiz.questions?.length || 0}`;
  const headerMeta = [topicText, countText].filter(Boolean).join('  •  ');
  if (headerMeta) {
    doc.font(getFont(headerMeta, false)).fontSize(10).fillColor('#475569').text(headerMeta);
    doc.moveDown(0.3);
  }

  if (quiz.description) {
    doc.font(getFont(quiz.description, false)).fontSize(9).fillColor('#64748b').text(quiz.description);
    doc.moveDown(0.4);
  }

  // Variant Banner & Student Fill Lines
  if (isAnswerKey) {
    doc.save();
    doc.rect(40, doc.y, doc.page.width - 80, 22).fill('#f1f5f9');
    doc.font(getFont('Answer Key', true)).fontSize(10).fillColor('#1e293b').text(
      'TEACHER ANSWER KEY & CONCEPT ANCHORS',
      45,
      doc.y - 17,
      { align: 'center', width: doc.page.width - 90 }
    );
    doc.restore();
    doc.moveDown(0.8);
  } else {
    // Blank student information lines
    doc.font(getFont('Name', false)).fontSize(10).fillColor('#334155');
    doc.text('Name: _________________________________    Date: ____________    Class: ____________');
    doc.moveDown(0.5);
    doc.font(getFont('Instructions', true)).fontSize(9).fillColor('#0f172a').text(
      'Instructions: Choose the one best answer for each question.'
    );
    doc.moveDown(0.6);
  }

  // Divider Line
  doc.strokeColor('#cbd5e1').lineWidth(0.8).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
  doc.moveDown(0.8);

  // Questions Loop
  const OPTION_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F'];
  const questions = quiz.questions || [];

  questions.forEach((q, qIndex) => {
    // Height estimation to keep question and its options together on the same page
    const optionCount = q.options?.length || 4;
    const estimatedHeight = 45 + optionCount * 24 + (isAnswerKey && explanations ? 35 : 0);
    ensureVerticalSpace(doc, estimatedHeight);

    // Question Number & Text
    const qNum = `${qIndex + 1}. `;
    const qText = q.questionText || '';
    const qFull = `${qNum}${qText}`;

    doc.font(getFont(qFull, true)).fontSize(11).fillColor('#0f172a');
    doc.text(qFull, { width: doc.page.width - 80 });
    doc.moveDown(0.4);

    // Options
    (q.options || []).forEach((opt, optIndex) => {
      const letter = OPTION_LETTERS[optIndex] || `${optIndex + 1}`;
      const isCorrect = isAnswerKey && optIndex === q.correctIndex;
      const rationale =
        isAnswerKey && explanations && !isCorrect && q.distractorRationales && q.distractorRationales[optIndex]
          ? q.distractorRationales[optIndex]
          : null;

      const optText = `${letter}. ${opt || ''}`;
      const optFont = getFont(opt, isCorrect);

      doc.save();
      if (isCorrect) {
        // Highlight correct option in answer key
        const boxY = doc.y - 2;
        doc.rect(45, boxY, doc.page.width - 90, 18).fill('#f0fdf4'); // green-50
        doc.strokeColor('#86efac').lineWidth(0.5).rect(45, boxY, doc.page.width - 90, 18).stroke();
        doc.font(optFont).fontSize(10).fillColor('#15803d'); // green-700
        doc.text(`[● ✓ CORRECT]  ${optText}`, 50, boxY + 3, { width: doc.page.width - 100 });
      } else {
        doc.font(optFont).fontSize(10).fillColor('#1e293b');
        doc.text(`(  )   ${optText}`, 50, doc.y, { width: doc.page.width - 100 });
      }
      doc.restore();

      // Distractor misconception rationale in answer key
      if (rationale) {
        doc.font(getFont(rationale, false)).fontSize(8).fillColor('#b45309'); // amber-700
        doc.text(`        ↳ Misconception: ${rationale}`, 50, doc.y, { width: doc.page.width - 100 });
      }
      doc.moveDown(0.3);
    });

    // Answer Key additions: Correct Answer line + Concept Anchor explanation
    if (isAnswerKey) {
      doc.moveDown(0.2);
      const correctLetter = OPTION_LETTERS[q.correctIndex] || `${q.correctIndex + 1}`;
      doc.font(getFont('Answer', true)).fontSize(9).fillColor('#15803d');
      doc.text(`Correct Answer: Option ${correctLetter}`);

      if (explanations && q.explanation) {
        doc.font(getFont(q.explanation, false)).fontSize(8.5).fillColor('#475569');
        doc.text(`Concept Anchor: ${q.explanation}`, { width: doc.page.width - 90 });
      }
    }

    doc.moveDown(0.8);
  });

  // End of Answers PDF: Answer Key Summary Table
  if (isAnswerKey && questions.length > 0) {
    ensureVerticalSpace(doc, 70);
    doc.strokeColor('#cbd5e1').lineWidth(0.5).moveTo(40, doc.y).lineTo(doc.page.width - 40, doc.y).stroke();
    doc.moveDown(0.6);

    doc.font(getFont('Quick Answer Key', true)).fontSize(11).fillColor('#0f172a').text('Quick Answer Key Table');
    doc.moveDown(0.4);

    const cols = 5;
    const colWidth = (doc.page.width - 80) / cols;
    let tableY = doc.y;

    questions.forEach((q, idx) => {
      const colIdx = idx % cols;
      if (idx > 0 && colIdx === 0) {
        tableY += 16;
        ensureVerticalSpace(doc, 20);
      }
      const letter = OPTION_LETTERS[q.correctIndex] || `${q.correctIndex + 1}`;
      const cellText = `Q${idx + 1}: ${letter}`;

      doc.font(getFont(cellText, true)).fontSize(9).fillColor('#1e293b').text(
        cellText,
        40 + colIdx * colWidth,
        tableY
      );
    });
  }

  // Stamp all pages with page numbers and footers
  stampFooters(doc, { getFont });

  doc.end();
  return doc;
}

/**
 * Generates Session Report or Student Progress PDF (F7)
 * Returns a readable stream
 */
export function generateSessionPdf(session, { targetPlayerId = null } = {}) {
  const isSingleStudent = Boolean(targetPlayerId);
  const metadataTitle = `${session.quizTitle || 'Quiz'} - ${isSingleStudent ? 'Student Report' : 'Class Report'}`;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 40, bottom: 40, left: 40, right: 40 },
    bufferPages: true,
    info: {
      Title: metadataTitle,
      Author: 'ReviseLive',
      Subject: 'Classroom Analytics',
      Creator: 'ReviseLive Analytics Engine'
    }
  });

  const { getFont } = setupDocumentFonts(doc);

  const maxStudents = env.PDF_MAX_STUDENTS || 300;
  const players = (session.players || []).slice(0, maxStudents);
  const targetPlayers = isSingleStudent
    ? players.filter((p) => p.playerId === targetPlayerId)
    : players;

  // 1. CLASS SUMMARY PAGE (only on full class export)
  if (!isSingleStudent) {
    doc.font(getFont(session.quizTitle, true)).fontSize(18).fillColor('#0f172a').text(
      session.quizTitle || 'Class Session Report'
    );
    doc.moveDown(0.2);

    const dateStr = session.startedAt ? new Date(session.startedAt).toLocaleDateString() : 'N/A';
    doc.font(getFont('Date', false)).fontSize(10).fillColor('#64748b').text(
      `Date: ${dateStr}   •   Students: ${players.length}   •   Room PIN: ${session.pin}`
    );
    doc.moveDown(0.6);

    // Summary KPI boxes
    const totalCorrect = players.reduce((sum, p) => sum + (p.correctCount || 0), 0);
    const totalAnswered = players.reduce((sum, p) => sum + (p.answeredCount || 0), 0);
    const classAccuracy = totalAnswered > 0 ? Math.round((totalCorrect / totalAnswered) * 100) : 0;
    const avgScore = players.length > 0 ? Math.round(players.reduce((sum, p) => sum + (p.finalScore || 0), 0) / players.length) : 0;

    const startY = doc.y;
    doc.rect(40, startY, 150, 40).fill('#f8fafc');
    doc.strokeColor('#e2e8f0').rect(40, startY, 150, 40).stroke();
    doc.font(getFont('Class Accuracy', false)).fontSize(8).fillColor('#64748b').text('CLASS ACCURACY', 48, startY + 6);
    doc.font(getFont('Accuracy', true)).fontSize(14).fillColor('#0f172a').text(`${classAccuracy}%`, 48, startY + 18);

    doc.rect(200, startY, 150, 40).fill('#f8fafc');
    doc.strokeColor('#e2e8f0').rect(200, startY, 150, 40).stroke();
    doc.font(getFont('Avg Score', false)).fontSize(8).fillColor('#64748b').text('AVERAGE SCORE', 208, startY + 6);
    doc.font(getFont('Score', true)).fontSize(14).fillColor('#0f172a').text(`${avgScore} pts`, 208, startY + 18);

    doc.y = startY + 50;

    // Retest before vs after summary if a retest was run
    if (session.retest && session.retest.questionIndexes?.length > 0) {
      doc.save();
      doc.rect(40, doc.y, doc.page.width - 80, 36).fill('#faf5ff'); // purple-50
      doc.strokeColor('#d8b4fe').rect(40, doc.y, doc.page.width - 80, 36).stroke();
      doc.font(getFont('Retest', true)).fontSize(9.5).fillColor('#7e22ce').text(
        session.retest.headline || 'Retest Round Improvement Summary',
        48,
        doc.y + 6
      );
      doc.font(getFont('Retest text', false)).fontSize(8.5).fillColor('#6b21a8').text(
        `Before: ${Math.round(session.retest.beforeAccuracy * 100)}%   →   After: ${Math.round(session.retest.afterAccuracy * 100)}%`,
        48,
        doc.y + 20
      );
      doc.restore();
      doc.y += 44;
    }

    // Flagged topics & misconceptions (Blindspot Radar)
    if (session.blindspotReport?.topics?.length > 0) {
      doc.moveDown(0.4);
      doc.font(getFont('Topics', true)).fontSize(11).fillColor('#0f172a').text('Topic Mastery Breakdown');
      doc.moveDown(0.3);

      session.blindspotReport.topics.forEach((t) => {
        const accPct = Math.round((t.accuracy || 0) * 100);
        const isWeak = accPct < 50;
        doc.font(getFont(t.topicTag, isWeak)).fontSize(9).fillColor(isWeak ? '#b91c1c' : '#334155');
        doc.text(`${t.topicTag}: ${accPct}% accuracy (${t.questionCount} questions)${isWeak ? '  [FLAGGED]' : ''}`);
      });
      doc.moveDown(0.4);
    }

    // Top Misconceptions
    if (session.blindspotReport?.topMisconceptions?.length > 0) {
      ensureVerticalSpace(doc, 45);
      doc.font(getFont('Top Misconceptions', true)).fontSize(11).fillColor('#0f172a').text('Top Misconceptions Identified');
      doc.moveDown(0.2);
      session.blindspotReport.topMisconceptions.slice(0, 3).forEach((m) => {
        doc.font(getFont(m.rationale, false)).fontSize(8.5).fillColor('#b45309').text(
          `• ${m.rationale} (${m.count} student${m.count === 1 ? '' : 's'})`
        );
      });
      doc.moveDown(0.4);
    }

    // Confident-Misconceptions (Certain & Wrong)
    if (session.blindspotReport?.confidentMisconceptions?.length > 0) {
      ensureVerticalSpace(doc, 45);
      doc.font(getFont('Confident Misconceptions', true)).fontSize(11).fillColor('#991b1b').text('High-Confidence Misconceptions (Certain & Wrong)');
      doc.moveDown(0.2);
      session.blindspotReport.confidentMisconceptions.slice(0, 3).forEach((cm) => {
        doc.font(getFont(cm.rationale, false)).fontSize(8.5).fillColor('#b91c1c').text(
          `• Q${cm.questionIndex + 1} (${cm.topicTag}): ${cm.confidentWrongPercent}% certainty while wrong. ${cm.rationale}`
        );
      });
      doc.moveDown(0.4);
    }

    // Item-Analysis Flags
    const flaggedQuestions = (session.questionStats || []).filter((qs) => qs.flags && qs.flags.length > 0);
    if (flaggedQuestions.length > 0) {
      ensureVerticalSpace(doc, 40);
      doc.font(getFont('Flags', true)).fontSize(10.5).fillColor('#0f172a').text('Item Analysis Flags');
      doc.moveDown(0.2);
      flaggedQuestions.slice(0, 4).forEach((fq) => {
        doc.font(getFont(fq.questionText, false)).fontSize(8.5).fillColor('#475569').text(
          `• Q${fq.questionIndex + 1} (${fq.topicTag}): ${fq.flags.join(', ')} (Accuracy: ${Math.round((fq.accuracy || 0) * 100)}%)`
        );
      });
      doc.moveDown(0.4);
    }

    // Class Roster Table
    ensureVerticalSpace(doc, 80);
    doc.moveDown(0.4);
    doc.font(getFont('Roster', true)).fontSize(11).fillColor('#0f172a').text('Class Standing & Results');
    doc.moveDown(0.3);

    // Table Header
    const rowH = 18;
    doc.rect(40, doc.y, doc.page.width - 80, rowH).fill('#f1f5f9');
    doc.font(getFont('Header', true)).fontSize(8.5).fillColor('#475569');
    doc.text('Rank', 48, doc.y + 5);
    doc.text('Student', 80, doc.y - 12);
    doc.text('Score', 240, doc.y - 12);
    doc.text('Solved', 320, doc.y - 12);
    doc.text('Accuracy', 420, doc.y - 12);
    doc.y += 18;

    players.forEach((p, rIdx) => {
      ensureVerticalSpace(doc, rowH);
      const acc = p.answeredCount > 0 ? Math.round((p.correctCount / p.answeredCount) * 100) : 0;
      doc.font(getFont(p.name, false)).fontSize(8.5).fillColor('#1e293b');
      doc.text(`#${p.rank || rIdx + 1}`, 48, doc.y + 4);
      doc.text(p.name || 'Anonymous', 80, doc.y - 11, { width: 150, ellipsis: true });
      doc.text(`${p.finalScore || 0}`, 240, doc.y - 11);
      doc.text(`${p.correctCount || 0} / ${p.answeredCount || 0}`, 320, doc.y - 11);
      doc.text(`${acc}%`, 420, doc.y - 11);
      doc.y += 16;
    });

    doc.addPage();
  }

  // 2. PER-STUDENT REPORT PAGES
  targetPlayers.forEach((player, pIdx) => {
    if (pIdx > 0) {
      doc.addPage();
    }

    // Student Header Card (truncate long name)
    const displayName = (player.name || 'Anonymous').slice(0, 40);
    doc.font(getFont(displayName, true)).fontSize(16).fillColor('#0f172a').text(displayName);
    doc.moveDown(0.2);
    doc.font(getFont('Meta', false)).fontSize(9.5).fillColor('#64748b').text(
      `Quiz: ${session.quizTitle}   •   Rank: #${player.rank} of ${players.length}   •   Score: ${player.finalScore} pts`
    );
    doc.moveDown(0.5);

    const pAcc = player.answeredCount > 0 ? Math.round((player.correctCount / player.answeredCount) * 100) : 0;
    doc.font(getFont('Accuracy', true)).fontSize(10.5).fillColor('#0f172a').text(`Accuracy: ${pAcc}% (${player.correctCount}/${player.answeredCount} solved)`);
    doc.moveDown(0.3);

    // Calibration line when confidence stats exist
    if (player.confidenceStats) {
      const { certain = 0, fairlySure = 0, guessing = 0 } = player.confidenceStats;
      doc.font(getFont('Calibration', false)).fontSize(8.5).fillColor('#475569').text(
        `Confidence Calibration: ${certain} Certain, ${fairlySure} Fairly Sure, ${guessing} Guessing`
      );
      doc.moveDown(0.4);
    }

    // Per-Topic Mastery Bars with explicit text percentages
    if (player.history && player.history.length > 0) {
      const studentTopicMap = new Map();
      player.history.forEach((h) => {
        const qStat = session.questionStats?.find((qs) => qs.questionIndex === h.questionIndex);
        const topic = qStat?.topicTag || 'General';
        if (!studentTopicMap.has(topic)) {
          studentTopicMap.set(topic, { correct: 0, total: 0 });
        }
        const data = studentTopicMap.get(topic);
        data.total += 1;
        if (h.isCorrect) data.correct += 1;
      });

      if (studentTopicMap.size > 0) {
        doc.font(getFont('Topic Mastery', true)).fontSize(10).fillColor('#0f172a').text('Topic Mastery:');
        doc.moveDown(0.2);
        studentTopicMap.forEach((val, topic) => {
          const tPct = Math.round((val.correct / val.total) * 100);
          doc.font(getFont(topic, false)).fontSize(8.5).fillColor('#334155').text(
            `• ${topic}: ${tPct}% mastery (${val.correct}/${val.total} correct)`
          );
        });
        doc.moveDown(0.4);
      }
    }

    // Topics to Revise (certain-and-wrong prioritized)
    if (player.missedTopics && player.missedTopics.length > 0) {
      doc.save();
      doc.rect(40, doc.y, doc.page.width - 80, 24).fill('#fef2f2'); // red-50
      doc.strokeColor('#fca5a5').rect(40, doc.y, doc.page.width - 80, 24).stroke();
      doc.font(getFont('Topics to Revise', true)).fontSize(9).fillColor('#991b1b').text(
        `Topics to Revise: ${player.missedTopics.join(', ')}`,
        48,
        doc.y + 6
      );
      doc.restore();
      doc.y += 32;
    }

    // Retest note if player participated
    if (session.retest) {
      const retestPlayer = session.retest.perPlayer?.find((rp) => rp.playerId === player.playerId);
      if (retestPlayer) {
        doc.font(getFont('Retest', true)).fontSize(9.5).fillColor('#7e22ce').text(
          `Retest Round: Solved ${retestPlayer.correct}/${retestPlayer.total} (${retestPlayer.score} pts earned)${retestPlayer.improvedCount ? ` • ${retestPlayer.improvedCount} question(s) improved!` : ''}`
        );
        doc.moveDown(0.4);
      }
    }

    // Table of Missed Questions
    if (!player.history || player.history.length === 0) {
      doc.moveDown(0.4);
      doc.font(getFont('Notice', false)).fontSize(9).fillColor('#64748b').text(
        'Per-question item detail is not available for this session.'
      );
    } else {
      const missed = player.history.filter((h) => !h.isCorrect && (!h.round || h.round === 'main'));
      if (missed.length === 0) {
        doc.moveDown(0.3);
        doc.font(getFont('Perfect', true)).fontSize(10).fillColor('#15803d').text('Perfect Score! No questions were missed in the main round.');
      } else {
        ensureVerticalSpace(doc, 40);
        doc.moveDown(0.3);
        doc.font(getFont('Missed Questions', true)).fontSize(11).fillColor('#0f172a').text(`Missed Questions (${missed.length})`);
        doc.moveDown(0.4);

        missed.forEach((m) => {
          ensureVerticalSpace(doc, 60);
          const qStat = session.questionStats?.find((qs) => qs.questionIndex === m.questionIndex);
          const qText = `Q${m.questionIndex + 1}: ${qStat?.questionText || 'Question'}`;
          const OPTION_LETTERS = ['A', 'B', 'C', 'D'];

          doc.font(getFont(qText, true)).fontSize(9).fillColor('#0f172a').text(qText, { width: doc.page.width - 90 });
          doc.moveDown(0.2);

          const studentAnsText =
            m.selectedIndex !== null && m.selectedIndex !== undefined
              ? `Option ${OPTION_LETTERS[m.selectedIndex] || m.selectedIndex + 1}${qStat?.options?.[m.selectedIndex] ? ` (${qStat.options[m.selectedIndex]})` : ''}`
              : 'No answer submitted';
          doc.font(getFont('Your Answer', false)).fontSize(8.5).fillColor('#b91c1c').text(
            `Your Answer: ${studentAnsText}`
          );

          if (qStat?.topDistractorRationale && m.selectedIndex === qStat.topDistractorIndex) {
            doc.font(getFont('Misconception', false)).fontSize(8).fillColor('#b45309').text(
              `  ↳ Misconception: ${qStat.topDistractorRationale}`
            );
          }

          if (qStat) {
            const correctLetter = OPTION_LETTERS[qStat.correctIndex] || `${qStat.correctIndex + 1}`;
            const correctOptText = qStat.options?.[qStat.correctIndex] ? ` (${qStat.options[qStat.correctIndex]})` : '';
            doc.font(getFont('Correct Answer', true)).fontSize(8.5).fillColor('#15803d').text(
              `Correct Answer: Option ${correctLetter}${correctOptText}`
            );

            if (qStat.explanation) {
              doc.font(getFont('Anchor', false)).fontSize(8).fillColor('#475569').text(
                `Concept Anchor: ${qStat.explanation}`
              );
            }
          }

          doc.moveDown(0.5);
        });
      }
    }
  });

  stampFooters(doc, { getFont });
  doc.end();
  return doc;
}
